module.exports = {
  apps: [
    {
      name: "backend",
      cwd: "./backend",
      script: "python",
      args: "-m uvicorn main:app --host 0.0.0.0 --port 8001 --reload",
      interpreter: "none",
      env: {
        PYTHONUNBUFFERED: "1",
      },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      out_file: "../logs/backend-out.log",
      error_file: "../logs/backend-error.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },
    {
      name: "frontend",
      cwd: "./frontend",
      script: "node",
      args: "node_modules/next/dist/bin/next dev --port 3015",
      interpreter: "none",
      env: {
        NODE_ENV: "development",
        PORT: "3015",
        NEXT_PUBLIC_API_URL: "http://localhost:8001",
        NEXT_PUBLIC_WS_URL: "ws://localhost:8001/ws/chat",
      },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 8000,
      listen_timeout: 10000,
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      out_file: "../logs/frontend-out.log",
      error_file: "../logs/frontend-error.log",
      merge_logs: true,
      max_size: "10M",
      retain: 5,
    },
  ],
};
